### ISSUE TITLE
Termux bug

### ISSUE THREAD

**Issue by slythno** [ankit0183/Wifi-Hacking#17]
![IMG_20210716_154120](https://user-images.githubusercontent.com/87435145/125932555-5bab453b-5bd8-433a-96b8-8bc588cb79a4.jpg)
![IMG_20210716_154153](https://user-images.githubusercontent.com/87435145/125932562-a740e63f-53f1-4e37-963d-a7879b5a84db.jpg)

My device is rooted and termux has root access.
can you help me through this ?

**Comment by ankit0183** [comment]
You need an External (Wifi Adapter )which supports monitor mode for malicious packets injects into the network.!
