### ISSUE TITLE
Wifi-hacking

### ISSUE THREAD

**Issue by adipratomo2608** [ankit0183/Wifi-Hacking#18]

**Comment by rokonn** [comment]
Bro..please tell me some tricks for non rooted..(in termux)

**Comment by adipratomo2608** [comment]
Just install proot

**Comment by adipratomo2608** [comment]
> Bro..please tell me some tricks for non rooted..(in termux)

Install proot:

$Pkg install proot

After install use this command:

$proot -0 $(which bash)

**Comment by rokonn** [comment]
Then??

**Comment by ankit0183** [comment]
> Then??

if you want to play with Security in android fone, you have to ROOT your Device first..!  

use Kali Nethunter OS https://www.kali.org/docs/nethunter/
