### ISSUE TITLE
how to get BSSID of network?

### ISSUE THREAD

**Issue by ArbitCode** [ankit0183/Wifi-Hacking#6]
by switching to option 4, there is showing error, It did not show the expected BSSID address of the network.

![image](https://user-images.githubusercontent.com/35590355/98568543-36f0dd00-22d7-11eb-91a1-c7ca1c263525.png)

Thank you to contribute it as an open source.

**Comment by ankit0183** [comment]
most of laptop inbuilt wifi adapter not support monitor mode ,You need to buy External wifi adapter which support monitor mode ,
Ralink RT3070, Atheros AR9271 etc..chipset adapter.
